### ISSUE TITLE
Internal Server Error if Referer is missing in request to /get-link

### ISSUE THREAD

**Issue by peterhellberg** [bluzi/jsonstore#10]
I think that the use of the `Referer` header in the backend code should be removed completely.

```
curl www.jsonstore.io/get-link
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>
```

The backend should not depend on the client to send a valid Referer header:
```
curl -H 'Referer: http://bogus.url' www.jsonstore.io/get-link
{"link":"http://bogus.url/fbbee72d1ac49a589480c578963aa13f71d53416510bdfd87974f300aa886282/"}
```

**Comment by bluzi** [comment]
Thanks for reporting, will have a look soon.

**Comment by medakk** [comment]
It might be preferable to use the Host header to construct the link, instead of Referer. [Host is mandatory in HTTP/1.1](https://serverfault.com/questions/163511/what-is-the-mandatory-information-a-http-request-header-must-contain).

Also, it think it would be useful to have an optional prefix to all the URLs,  so someone can host jsonstore at a different endpoint other than the base, like http://www.example.com/jsonstore/get-link

**Comment by peterhellberg** [comment]
I don't think that _any_ header should be used. Instead the base URL should be loaded from an environment variable. https://12factor.net/config

**Comment by medakk** [comment]
That logic can be moved to the client, which is aware of the endpoint at which the API exists.

**Comment by akshendra** [comment]
Using an environment variables seems like a good idea. We can bootstrap that variable (base url) into the client while building for different environments.

**Comment by akshendra** [comment]
@bluzi thinking about using a .env, moving firebase config into it as well.

**Comment by bluzi** [comment]
@akshendra solved this by changing `/get-link` to `/get-token`. It's already deployed.
