### ISSUE TITLE
will it be used infinitely?

### ISSUE THREAD

**Issue by csrgxtu** [bluzi/jsonstore#30]

**Comment by csrgxtu** [comment]
without any limitations

**Comment by bluzi** [comment]
We do have some limitations, jsonstore.io is meant to be used as a free service for open source projects, and it is not made to serve large projects with lots of traffic.

We also don't have any expiration dates, we're planning on keeping the service live for as long as we can, and so far I can't think of a reason we'll shut it down, since things are going great.

Hope I answered your questions.
